### ISSUE TITLE
AEG Robot always offline

### ISSUE THREAD

**Issue by Niklas31** [thoukydides/homebridge-aeg-robot#13]
### Description of Issue

When checking on Home App, my robot always seems to be not responding.
When checking Hoobs logs, 2 of 9 servers are reporting issues:

`7/19/2023, 7:55:15 AMAspirador PonteHomebridge AEG Robot VacuumERROR2 of 9 AEG API servers have problems:`
`7/19/2023, 7:55:15 AMAspirador PonteHomebridge AEG Robot VacuumERRORhcsda.FirmwareService               Unknown                  Unknown     prod        513  I am dead!`
`7/19/2023, 7:55:15 AMAspirador PonteHomebridge AEG Robot VacuumERRORTelemetryService.ImportHost         Unknown                  Unknown     prod        513  I am dead!`
`7/19/2023, 7:55:15 AMAspirador PonteHomebridge AEG Robot VacuumERROR[Server health] Error: AEG API servers are reporting issues (2 of 9)`

I wonder if it has something to do with Electrolux changing servers and breaking plugin or something else. Electrolux app seem to be working fine.

Since this is a API problem, here is the API run test log:
[API test Log.txt](https://github.com/thoukydides/homebridge-aeg-robot/files/12095125/API.test.Log.txt)

And the Debug log:
[Debug log.txt](https://github.com/thoukydides/homebridge-aeg-robot/files/12095140/Debug.log.txt)

Thanks for the support.

### Plugin Version

0.2.5

### AEG/Electrolux Appliance(s)

AEG PI92-4SGM

### HomeKit App(s)

Apple Home

### Diagnostic Checks

- [X] AEG iPhone app is able to control the appliance.

### Log File

```shell
7/19/2023, 9:10:42 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ WARNING ] Unexpected fields in AEG API response:
7/19/2023, 9:10:42 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ WARNING ] GET /one-account-user/api/v1/users/current
7/19/2023, 9:10:42 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ WARNING ] └─ response.phoneNumbers is extraneous
7/19/2023, 9:10:43 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ WARNING ] Request will not be retried (POST is not idempotent)
7/19/2023, 9:10:43 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ ERROR ] [API test #9] getWebShopURLs(["900921353109007781100106"])
7/19/2023, 9:10:43 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ ERROR ] [API test #9] AEG API Status Code Error: [400 Bad Request] BadRequest: Undefined. (400000)
7/19/2023, 9:10:44 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ WARNING ] Unexpected fields in AEG API response:
7/19/2023, 9:10:44 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ WARNING ] GET /appliance/api/v2/appliances/900921353109007781100106/info
7/19/2023, 9:10:44 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ WARNING ] └─ response.productArea is extraneous
7/19/2023, 9:10:49 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ ERROR ] 1 of 17 API tests failed
7/19/2023, 9:10:49 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ ERROR ] API test #9: getWebShopURLs(["900921353109007781100106"])
7/19/2023, 9:10:49 AM Aspirador Bridge Homebridge AEG Robot Vacuum [ ERROR ]     AEG API Status Code Error: [400 Bad Request] BadRequest: Undefined. (400000)
```

**Comment by thoukydides** [comment]
It looks like there are a few different issues here...

I see that the logs contain the message `Removing obsolete service "HOOBS"` which suggests that there may be a compatibility issue when used with `HOOBS`. It looks like HOOBS is adding something to the accessory created by this plugin, which this plugin then removes because it is unexpected. I have no idea what impact that might have, but it probably isn't good. However, this is a Homebridge plugin, not a HOOBS plugin. I do not support use of this plugin with HOOBS, so will not be investigating that any further. If you want to pursue it then please contact HOOBS support instead.

You have not actually provided a log with debug enabled, i.e. with the `-D` option on the Homebridge command line. This significantly reduces the information available to diagnose what might be going wrong.

The server status is simply what the API reports:
* `hcsda.FirmwareService` has been reporting problems since 23rd March. (See issue #6)
* `TelemetryService.ImportHost` has been reporting problems since 5th June.

The AEG iPhone app receives exactly the same response, with those two servers similarly reporting `513 I am dead!` status. These failures do not appear to affect operation of either the AEG app or this plugin. Hence, just ignore those messages.

The `Unexpected fields in AEG API response` warnings are examples of where the API has returned additional information that this plugin was not expecting. The extra information is ignored without affecting operation of this plugin, other than the warnings in the log. Checking the log file for my own installation I see those same issues (which is fortunate since you have not actually provided a log with debug enabled, using the Homebridge `-D` command line option). I will update the plugin to accept the additional fields.

The final problem in your log files is that the `getWebShopURLs` API method is returning a `400 Bad Request` result. I cannot reproduce that issue so have no way to debug it. However, that API is not actually used during normal operation, so it won't affect operation of the plugin.

Other than the `Removing obsolete service "HOOBS"` issue, there is nothing in the log files that you provided that should adversely affect correct operation of this plugin.

**Comment by thoukydides** [comment]
The `extraneous` field messages should be fixed in v0.2.7.

I will not be doing anything about HOOBS compatibility.

That leaves the `400 Bad Request` result for the `getWebShopURLs` API method. If you can add `"debug": ["Run API Tests", "Log API Headers", "Log API Bodies", "Log Debug as Info"]` to the `config.json` file and provide a log showing that problem again then I will investigate further. However, as I mentioned, that API method isn't actually used by this plugin - it is just tested for completeness - so this isn't really important. Strange that I don't see the same issue though.

**Comment by Niklas31** [comment]
Thanks for the quick reply. I will try to change from hoobs to proper homebridge and will update you if error persist. By the way, thanks for the plugin, since they killed IFTTT support, you have saved my robot.
